### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DraugDev** [appleboy/CodeIgniter-reCAPTCHA#2]
Hello,
how to use your library with form_validation?

Thanks!

**Comment by DraugDev** [comment]
I've got this one.

$this->form_validation->set_rules('g-recaptcha', 'Recaptcha', 'required' . $recaptcha = $this->input->post('g-recaptcha-response'));

**Comment by Luckyfella73** [comment]
Have a look at the example:
`https://github.com/appleboy/CodeIgniter-reCAPTCHA/blob/master/example/controller/test.php`

I would set up a custom callback function and add that to the validation rules.

**Comment by DraugDev** [comment]
Hay @Luckyfella73,
thanks, ill try.
