### ISSUE TITLE
Missing 'id' for the reCAPTCHA <div>

### ISSUE THREAD

**Issue by abuzant** [appleboy/CodeIgniter-reCAPTCHA#4]
Please change line #158 in /libraries/Recaptcha.php 

from:
`return '<div class="g-recaptcha" '.$html.'></div>';`

to:
`return '<div id="g-recaptcha" class="g-recaptcha" '.$html.'></div>';`

to give the DIV an ID so it can be accessible VIA jQuery and/or other frameworks.

**Comment by appleboy** [comment]
@abuzant I will take it.

**Comment by appleboy** [comment]
@abuzant Maybe you should try

```php
getWidget(array("id" => "g-recaptcha"))
```
